// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNSJ9NPvZnKZV2Hli_99eYwwFIArgGrmY',
    appId: '1:478874876989:web:d1ddbbd8d5880288dcfe54',
    messagingSenderId: '478874876989',
    projectId: 'designsprint-team6',
    authDomain: 'designsprint-team6.firebaseapp.com',
    storageBucket: 'designsprint-team6.appspot.com',
    measurementId: 'G-XN98065EZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHpdCeovewNea7IeCm1wxlxRlWSij6Hm0',
    appId: '1:478874876989:android:fcf5bbd6a75d16d6dcfe54',
    messagingSenderId: '478874876989',
    projectId: 'designsprint-team6',
    storageBucket: 'designsprint-team6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrIcfKwx4nMahQyQPERL7gYVd1_sMD_6U',
    appId: '1:478874876989:ios:19bab68c38cda912dcfe54',
    messagingSenderId: '478874876989',
    projectId: 'designsprint-team6',
    storageBucket: 'designsprint-team6.appspot.com',
    iosClientId: '478874876989-th61cl7hm9vvab3k9t45ldhd8ta9uf2t.apps.googleusercontent.com',
    iosBundleId: 'com.example.cur',
  );
}
